# check-briefing-model.ps1 -- preflight check for the daily Telegram briefing.
#
# THE PROBLEM: llama-server serves WHATEVER model is currently loaded and
# IGNORES the "model" field the client asks for. Verified on this machine:
# we requested "gemma-4-26b-qat" while qwen3-coder-30b was loaded, and the
# request succeeded normally -- answered by qwen.
#
# CONSEQUENCE: if you run send_briefing.bat while in coding mode
# (start-ai-coder.bat), the 6 daily messages are generated by a CODING model,
# with no error at all -- just noticeably worse market analysis.
#
# Run this BEFORE the briefing:  powershell -File check-briefing-model.ps1
# Exit 0 = correct model, safe to send.  Exit 1 = wrong model or server down.
#
# ASCII-only on purpose: the Windows console codepage mangles Greek output.

$expected = $env:BRIEFING_MODEL
if (-not $expected) { $expected = "gemma-4-26b-qat" }

try {
    $r = Invoke-RestMethod -Uri "http://localhost:8080/v1/models" -TimeoutSec 8
    $served = $r.data[0].id
}
catch {
    Write-Host "[preflight] ERROR: llama-server is not responding on :8080." -ForegroundColor Red
    Write-Host "            Run start-ai.bat first (market mode / gemma)." -ForegroundColor Yellow
    exit 1
}

if ($served -eq $expected) {
    Write-Host "[preflight] OK - loaded model: $served (correct for briefing)" -ForegroundColor Green
    exit 0
}

Write-Host "[preflight] WARNING - WRONG MODEL LOADED" -ForegroundColor Red
Write-Host "            loaded  : $served"
Write-Host "            expected: $expected"
Write-Host ""
Write-Host "  The briefing WOULD STILL BE SENT, generated by the wrong model," -ForegroundColor Yellow
Write-Host "  with no error. Market analysis quality would be degraded." -ForegroundColor Yellow
Write-Host ""
Write-Host "  Fix: run start-ai.bat (loads gemma), then send the briefing." -ForegroundColor Cyan
exit 1
